name: CD

on:
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Build app with version
        run: make build VERSION=${{ steps.tagName.outputs.tag }}
      - name: Build app without version
        run: make build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push version to Docker Hub
        run: make push VERSION=${{ steps.tagName.outputs.tag }}
      - name: Push latest to Docker Hub
        run: make push